name: CI Simple

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  deploy-10:
    runs-on: ubuntu-latest
    needs: build
    environment: STAGE
    container: python:3.9.0-alpine
    steps:
      - uses: actions/checkout@v3
      - run: ls -alH
